CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/ActualizarPregunta.cshtml.cs
using FastshippingCar.Web.Models;
using FastshippingCar.Web.Models.Dao.Intefaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace FastshippingCar.Web.Pages
{
    public class ActualizarPreguntaModel : PageModel
    {
        private readonly IServiceGenerico<PqrsProductoModel> _pqrsPregunta;

        public ActualizarPreguntaModel(IServiceGenerico<PqrsProductoModel> pqrsPregunta)
        {
            _pqrsPregunta = pqrsPregunta;
        }

        [BindProperty]
        public PqrsProductoModel PqrsPregunta { get; set; }
        public async Task OnGetAsync(string id)
        {
            PqrsPregunta = await _pqrsPregunta.Tomar(id);
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _pqrsPregunta.Actualizar(id, PqrsPregunta);
            return RedirectToPage("/EditarPregunta");
        }
    }
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/ActualizarUsuario.cshtml.cs
using System.Threading.Tasks;
using FastshippingCar.Web.Dto;
using FastshippingCar.Web.Services.Interfaces;
using Firebase.Auth;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FastshippingCar.Web.Pages
{
    public class ActualizarUsuarioModel : PageModel
    {

        private readonly IUsuarioService _usuarioService;
        private readonly FastshippingCar.Web.Models.Dao.Intefaces.IServiceGenerico<FastshippingCar.Web.Models.UsuarioModel> _usuarioGenerico;

        [BindProperty]
        public UsuarioDto Usuario { get; set; }

        public ActualizarUsuarioModel(IUsuarioService usuarioService,FastshippingCar.Web.Models.Dao.Intefaces.IServiceGenerico<FastshippingCar.Web.Models.UsuarioModel> usuarioGenerico)
        {
            _usuarioService = usuarioService;
            _usuarioGenerico = usuarioGenerico;

        }

        
        public async Task OnGetAsync()
        {
           var objUser= await _usuarioGenerico.Tomar(FastshippingCar.Web.Common.Helpers.UserId(User));
            Usuario = new UsuarioDto {
                Email = objUser.Email,
                NumeroDocumento = objUser.NumeroDocumento,
                Nombre = objUser.Nombre,
                Apellido = objUser.Apellido,
                RolId = objUser.RolId,
                Telefono = objUser.Telefono,
                Direccion =objUser.Direccion
            } ;
        }

        
        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                     
                await _usuarioService.ActualizarUsuario(Usuario);

                return RedirectToPage("./Index");
            }
            catch (FirebaseAuthException e)
            {
                switch (e.Reason)
                {
                    case AuthErrorReason.Undefined:
                        TempData["msg"] = "<script>alert('Indefinido.');</script>";
                        break;
                    case AuthErrorReason.OperationNotAllowed:
                        TempData["msg"] = "<script>alert('Operación no permitida.');</script>";
                        break;
                    case AuthErrorReason.UserDisabled:
                        TempData["msg"] = "<script>alert('Usuario deshabilitado.');</script>";
                        break;
                    case AuthErrorReason.UserNotFound:
                        TempData["msg"] = "<script>alert('Usuario no encontrado.');</script>";
                        break;
                    case AuthErrorReason.InvalidProviderID:
                        TempData["msg"] = "<script>alert('ID de proveedor no válido.');</script>";
                        break;
                    case AuthErrorReason.InvalidAccessToken:
                        TempData["msg"] = "<script>alert('Token de acceso inválido.');</script>";
                        break;
                    case AuthErrorReason.LoginCredentialsTooOld:
                        TempData["msg"] = "<script>alert('Credenciales de inicio de sesión demasiado viejas.');</script>";
                        break;
                    case AuthErrorReason.MissingRequestURI:
                        TempData["msg"] = "<script>alert('URI de solicitud faltante.');</script>";
                        break;
                    case AuthErrorReason.SystemError:
                        TempData["msg"] = "<script>alert('Error del sistema.');</script>";
                        break;
                    case AuthErrorReason.InvalidEmailAddress:
                        TempData["msg"] = "<script>alert('Dirección de correo electrónico no válida.');</script>";
                        break;
                    case AuthErrorReason.MissingPassword:
                        TempData["msg"] = "<script>alert('Digite la contraseña.');</script>";
                        break;
                    case AuthErrorReason.WeakPassword:
                        TempData["msg"] = "<script>alert('Contraseña débil.');</script>";
                        break;
                    case AuthErrorReason.EmailExists:
                        TempData["msg"] = "<script>alert('Existe el email.');</script>";
                        break;
                    case AuthErrorReason.MissingEmail:
                        TempData["msg"] = "<script>alert('Email no encontrado.');</script>";
                        break;
                    case AuthErrorReason.UnknownEmailAddress:
                        TempData["msg"] = "<script>alert('Dirección de Email desconocida.');</script>";
                        break;
                    case AuthErrorReason.WrongPassword:
                        TempData["msg"] = "<script>alert('Contraseña incorrecta.');</script>";
                        break;
                    case AuthErrorReason.TooManyAttemptsTryLater:
                        TempData["msg"] = "<script>alert('Demasiados intentos,por favor intente más tarde.');</script>";
                        break;
                    case AuthErrorReason.MissingRequestType:
                        TempData["msg"] = "<script>alert('Falta el tipo de solicitud');</script>";
                        break;
                    case AuthErrorReason.ResetPasswordExceedLimit:
                        TempData["msg"] = "<script>alert('Restablecer contraseña, excedió el límite.');</script>";
                        break;
                    case AuthErrorReason.InvalidIDToken:
                        TempData["msg"] = "<script>alert('Token de ID inválido');</script>";
                        break;
                    case AuthErrorReason.MissingIdentifier:
                        TempData["msg"] = "<script>alert('Identificador faltante.');</script>";
                        break;
                    case AuthErrorReason.InvalidIdentifier:
                        TempData["msg"] = "<script>alert('Identificador no válido.');</script>";
                        break;
                    case AuthErrorReason.AlreadyLinked:
                        TempData["msg"] = "<script>alert('Ya se encuentra la cuenta vinculada.');</script>";
                        break;
                    default:
                        break;
                }

                return Page();
            }
        }
    }
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/CrearPregunta.cshtml.cs
using FastshippingCar.Web.Models;
using FastshippingCar.Web.Models.Dao.Intefaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace FastshippingCar.Web.Pages
{
    public class CrearPreguntaModel : PageModel
    {
        [BindProperty]
        public PqrsProductoModel PqrsPregunta { get; set; }
        public async Task<IActionResult> OnPostAsync([FromServices] IServiceGenerico<PqrsProductoModel> pqrsPregunta)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await pqrsPregunta.Crear(PqrsPregunta);
            return RedirectToPage("/EditarPregunta");
        }
    }
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/MisPedidos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FastshippingCar.Web.Common;
using FastshippingCar.Web.Dto;
using FastshippingCar.Web.Models;
using FastshippingCar.Web.Models.Dao.Intefaces;
using FastshippingCar.Web.Models.Enums;
using FastshippingCar.Web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FastshippingCar.Web.Pages
{
    public class MisPedidosModel : PageModel
    {
        private readonly IServiceGenerico<HistorialCompraModel> _historialCompra;
        private readonly IServiceGenerico<ProductoModel> _producto;


        public MisPedidosModel(IServiceGenerico<HistorialCompraModel> historialCompra
            , IServiceGenerico<ProductoModel> producto)
        {
            _historialCompra = historialCompra;
            _producto = producto;
            HistorialProductos = new List<HistorialCompraDto>();
        }

        [BindProperty]
        public List<HistorialCompraDto> HistorialProductos { get; set; }
        [BindProperty]
        public HistorialCompraModel HistorialCompra { get; set; }

        public async Task OnGetAsync([FromServices] ICalificacionProductoService calificacionProductoService)
        {
            HistorialProductos = new List<HistorialCompraDto>();
            var compras = await _historialCompra.Consultar();
            var historiales = compras.Where(x => x.UsuarioId == Helpers.UserId(User) && x.EstadoCompra != EstadoCompra.PendientePago).ToList();
            foreach (var historial in historiales)
            {
                HistorialProductos.Add(new HistorialCompraDto
                {
                    HistorialCompra = historial,
                    ProductoPuntuacion = await calificacionProductoService.ConsultarCalificacionProducto(historial.Producto.Id)
                });
            }
        }

        public async Task<IActionResult> OnPostCancelarAsync()
        {
            var compra = await _historialCompra.Tomar(HistorialCompra.Id);
            compra.EstadoCompra = EstadoCompra.PagoCancelado;
            await _historialCompra.Actualizar(compra.Id, compra);
            return RedirectToPage("/MisPedidos");
        }

        public async Task<IActionResult> OnGetCalificarAsync([FromServices] IServiceGenerico<ProductoPuntuacionModel> productoPuntuacion, [FromQuery] string id, [FromQuery] int valor)
        {
            var puntuacion = new ProductoPuntuacionModel
            {
                ProductoId = id,
                UsuarioId = Helpers.UserId(User),
                ValorPuntuacion = valor
            };
            await productoPuntuacion.Crear(puntuacion);
            return RedirectToPage("/MisPedidos");
        }
    }
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/detalleProducto.cshtml.cs
using FastshippingCar.Web.Common;
using FastshippingCar.Web.Dto;
using FastshippingCar.Web.Models;
using FastshippingCar.Web.Models.Dao.Intefaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace FastshippingCar.Web.Pages
{
    public class detalleProductoModel : PageModel
    {
        private readonly ILogger<detalleProductoModel> _logger;
        private readonly IServiceGenerico<ProductoModel> _productoService;
        private readonly IServiceGenerico<CarritoCompraModel> _carritoCompra;
        private readonly IServiceGenerico<UsuarioModel> _usuario;
        private readonly IServiceGenerico<VendedorModel> _vendedor;
        private readonly IServiceGenerico<TiendaModel> _tienda;

        public detalleProductoModel(ILogger<detalleProductoModel> logger
            , IServiceGenerico<ProductoModel> productoService
            , IServiceGenerico<CarritoCompraModel> carritoCompra
            , IServiceGenerico<UsuarioModel> usuario
            , IServiceGenerico<VendedorModel> vendedor
            , IServiceGenerico<TiendaModel> tienda)
        {
            _logger = logger;
            _productoService = productoService;
            _carritoCompra = carritoCompra;
            _usuario = usuario;
            _vendedor = vendedor;
            _tienda = tienda;
        }
        [BindProperty]
        public ContactarVendedorDto ContactarVendedor { get; set; }
        public VendedorDto Vendedor { get; set; }
        [BindProperty]
        public ProductoModel Producto { get; set; }
        public async Task OnGetAsync(string id)
        {
            Producto = await _productoService.Tomar(id);
            await CargarVendedor();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Producto = await _productoService.Tomar(Producto.Id);
            await CargarVendedor();
            var dato = new CarritoCompraModel
            {
                UsuarioId = Helpers.UserId(User),
                ProductoId = Producto.Id,
                Pagado = false
            };
            await _carritoCompra.Crear(dato);
            return RedirectToPage("/misProductos");
        }

        public async Task<IActionResult> OnPostAdicionarFavoritoAsync([FromServices] IServiceGenerico<ProductoFavoritoModel> productoFavorito)
        {
            var dato = new ProductoFavoritoModel
            {
                UsuarioId = Helpers.UserId(User),
                ProductoId = Producto.Id
            };
            await productoFavorito.Crear(dato);
            return RedirectToPage("/detalleProducto", new { id = Producto.Id });
        }

        private async Task CargarVendedor()
        {
            var tienda = await _tienda.Tomar(Producto.TiendaId);
            var vendedor = await _vendedor.Tomar(tienda.VendedorId);
            if (vendedor != null)
            {
                var usuario = await _usuario.Tomar(vendedor.UsuarioId);
                Vendedor = new VendedorDto
                {
                    Vendedor = vendedor,
                    Usuario = usuario
                };
                ContactarVendedor = new ContactarVendedorDto
                {
                    VendedorId = tienda.VendedorId
                };
            }

        }
    }
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/informacionPago.cshtml.cs
using FastshippingCar.Web.Common;
using FastshippingCar.Web.Dto;
using FastshippingCar.Web.Models;
using FastshippingCar.Web.Models.Context;
using FastshippingCar.Web.Models.Dao.Intefaces;
using FastshippingCar.Web.Models.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FastshippingCar.Web.Pages
{
    public class informacionPagoModel : PageModel
    {
        private readonly IServiceGenerico<CarritoCompraModel> _carritoCompra;
        private readonly IServiceGenerico<ProductoModel> _producto;


        public informacionPagoModel(IServiceGenerico<CarritoCompraModel> carritoCompra
            , IServiceGenerico<ProductoModel> producto)
        {
            _carritoCompra = carritoCompra;
            _producto = producto;
        }

        public List<CarritoCompraModel> CarritoCompras { get; set; }
        public List<ProductoModel> Productos { get; set; }
        [BindProperty]
        public FormularioPagoDto FormularioPago { get; set; }

        public async Task OnPostAsync()
        {
            CarritoCompras = new List<CarritoCompraModel>();
            Productos = new List<ProductoModel>();
            var compras = await _carritoCompra.Consultar();
            foreach (var compra in compras.Where(x => x.UsuarioId == Helpers.UserId(User) && !x.Pagado))
            {
                CarritoCompras.Add(compra);
                Productos.Add(await _producto.Tomar(compra.ProductoId));
            }
            FormularioPago.SendCost = 10000;
        }

        public async Task<IActionResult> OnPostPagarAsync([FromServices] SendGridEmail sendGrid
            , [FromServices] IServiceGenerico<UsuarioModel> usuario
            , [FromServices] IServiceGenerico<TiendaModel> tienda
            , [FromServices] IServiceGenerico<HistorialCompraModel> historialCompra
            , [FromForm] string[] idCarrito)
        {
            var infoUsuario = await usuario.Tomar(Helpers.UserId(User));
            foreach (var carrito in idCarrito)
            {
                var dato = await _carritoCompra.Tomar(carrito);
                var infoTienda = await tienda.Tomar(dato.TiendaId);
                var vendedor = await usuario.Tomar(infoTienda.VendedorId);
                var producto = await _producto.Tomar(dato.ProductoId);
                dato.Pagado = true;
                await _carritoCompra.Actualizar(carrito, dato);
                var historial = new HistorialCompraModel
                {
                    TiendaId = infoTienda.Id,
                    UsuarioId = Helpers.UserId(User),
                    ProductoId = producto.Id,
                    Producto = producto,
                    EstadoCompra = EstadoCompra.PendienteEnvio
                };
                await historialCompra.Crear(historial);
                await sendGrid.SendMail("Cliente - Compra de productos", $"Producto comprado: {dato.ProductoId}", infoUsuario.Email, vendedor.Email);
                await sendGrid.SendMail("Vendedor - Compra de productos", $"Producto comprado: {dato.ProductoId}", vendedor.Email, vendedor.Email);
            }
            return RedirectToPage("/misProductos");
        }
    }
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/ActualizarPregunta.cshtml
@page "{id}"
@model FastshippingCar.Web.Pages.ActualizarPreguntaModel
@{
    ViewData["Title"] = "CrearPregunta";
}

<div class="container py-3">
    <div class="col-md-12">
        <h1 class="text-center" id="titulo">Actualizar Pregunta</h1>
        <form method="post">
            <div class="form-row">
                <div class="form-group col-md-6 offset-md-3">
                    <label for="inputEmail4" id="titulo">Titulo</label>
                    <input class="form-control" id="inputEmail4" asp-for="PqrsPregunta.Titulo">
                </div>
                <div class="form-group col-md-6 offset-md-3">
                    <label for="DescripcionPregunta" id="titulo">Descripción</label>
                    <textarea class="form-control" id="DescripcionPregunta" rows="4" aria-describedby="passwordHelpBlock" asp-for="PqrsPregunta.Mensaje"></textarea>
                    <small id="passwordHelpBlock" class="form-text text-muted">
                        De una forma breve, de respuesta a la pregunta
                    </small>
                </div><br />
                <div class="col-lg-6 offset-md-3">
                    <div class="btn-group " role="group">
                        <button type="submit" class="btn btn-lg btn-success">Editar</button>
                        <button type="button" class="btn btn-lg btn-danger" href="/Index">Cancelar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/ActualizarUsuario.cshtml
@page
@model FastshippingCar.Web.Pages.ActualizarUsuarioModel
@{
    ViewData["Title"] = "ActualizarUsuario";
}



<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/floating-labels/">

    <!-- Bootstrap core CSS -->
    <link href="~/lib/bootstrap/bootstrap.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        $(function () {
            $('#indicadorContrasena').change(function () {
                if (!$(this).prop('checked')) {
                    $('#dvOcultar').hide();
                    $('#contrasena').val('');
                } else {
                    $('#dvOcultar').show();
                    $('#contrasena').val('');
                }
            })

            $('#dvOcultar').hide(); //oculto mediante id


            //$('#actualizar').click(function () {
            //    if ($('#contrasena').val) {
            //       return alert("Por favor digite la contraseña");
                    
            //    }               
            //})



        })
    </script>

</head>

<body>

    <div class="container:" style="margin-left:120px">


        <h1 id="titulo" style="margin-left:440px" class="h3 mb-3 font-weight-normal">Actualizar Usuario:</h1>


        <form method="post" style="margin-left:200px">
            <div class="text-danger"></div>
            <div class="form-group" style="margin-left:100px">
                <label for="usr">Nombre *:</label>
                <input style="width:500px" class="form-control" id="nombre" placeholder="nombre" name="nombre" asp-for="Usuario.Nombre">
                <span class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-left:100px">
                <label for="usr">Apellido *:</label>
                <input type="text" style="width:500px" class="form-control" id="apellido" placeholder="Apellido" name="apellido" asp-for="Usuario.Apellido">
            </div>
            <div class="form-group" style="margin-left:100px">
                @*<label for="email">Correo *:</label>*@
                <input type="hidden" style="width:500px" class="form-control" id="correo" placeholder="Correo" name="email" asp-for="Usuario.Email">
            </div>

            <div class="form-group" style="margin-left:100px">
                <label for="usr"> Documento de Identificacion *:</label>
                <input type="text" style="width: 500px" class="form-control " id="numeroDocumento" placeholder="Documento Identificacion" name="numeroDocumento" asp-for="Usuario.NumeroDocumento">
            </div>
            <div class="form-group" style="margin-left:100px">
                <label for="usr">Teléfono *:</label>
                <input type="text" style="width:500px" class="form-control" id="telefono" placeholder="Telefono" name="telefono" asp-for="Usuario.Telefono">
            </div>

            <div class="form-group" style="margin-left:100px">
                <label for="usr">Dirección *:</label>
                <input type="text" style="width:500px" class="form-control" id="telefono" placeholder="Telefono" name="direccion" asp-for="Usuario.Direccion">
            </div>


            <div class="form-group custom-checkbox" style="margin-left:125px">
                <input type="checkbox" class="custom-control-input" id="indicadorContrasena">
                <label class="custom-control-label" for="indicadorContrasena">Cambiar contraseña</label>

            </div>


            



            <div class="form-group" style="margin-left:100px" id="dvOcultar">
                <label for="pwd">Nueva Contraseña *:</label>
                <input type="password" style="width:500px" class="form-control" id="contrasena" placeholder="Nueva Contraseña " name="contrasena" asp-for="Usuario.Contrasena">
            </div>



            @*<div class="form-group" style="margin-left:100px">
            <label for="pwd">Validar contraseña *:</label>
            <input type="password" style="width:500px" class="form-control" id="pwd" placeholder="Validar Contraseña " name="contrasena" asp-for="Usuario.Contrasena">

        </div>*@

            <button type="submit" style="margin-left:100px" id="actualizar" class="btn btn-primary">Actualizar </button>
            <button type="submit" class="btn btn-primary" href="  "> Cancelar </button>
        </form>
    </div>

</body>
</html>

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/ContactarVendedor.cshtml
@page "{id}"
@model FastshippingCar.Web.Pages.ContactarVendedorModel
@{
    ViewData["Title"] = "ContactarVendedor";
}

<h1>ContactarVendedor</h1>

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/HistorialCompras.cshtml
@page
@model FastshippingCar.Web.Pages.HistorialComprasModel
@{
    ViewData["Title"] = "HistorialCompras";
}

CodigoFuente/FastshippingCar/FastshippingCar.Web/Pages/MisPedidos.cshtml
@page
@model FastshippingCar.Web.Pages.MisPedidosModel
@{
    ViewData["Title"] = "MisPedidos";
}
<div class="container py-3">
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-light" role="alert">
                <h4 class="alert-heading" id="titulo">Productos adquiridos<span class="badge badge-info">@(Model.HistorialProductos?.Count ?? 0)</span> </h4>
                @if (Model.HistorialProductos != null)
                {
                    @foreach (var producto in Model.HistorialProductos)
                    {

                        <div class="card mb-3">
                            <div class="row no-gutters">
                                <div class="col-md-6">
                                    <div class="card-body">
                                        <h5 class="card-title" id="titulo">@producto.HistorialCompra.Producto.Nombre</h5>
                                        <p class="card-text">@producto.HistorialCompra.Producto.Resumen</p>

                                    </div>
                                </div>
                                <div class="col-md-2">
                                    @switch (producto.HistorialCompra.EstadoCompra)
                                    {
                                        case Models.Enums.EstadoCompra.PendientePago:
                                            <label>Estado: Pendiente de pago</label>
                                            break;
                                        case Models.Enums.EstadoCompra.PendienteEnvio:
                                            <label>Estado: Pendiente de envio</label>
                                            break;
                                        case Models.Enums.EstadoCompra.PagoCancelado:
                                            <label>Estado: Cancelado</label>
                                            break;
                                        case Models.Enums.EstadoCompra.PedidoEnviado:
                                            <label>Estado: Enviado</label>
                                            break;
                                        case Models.Enums.EstadoCompra.Finalizado:
                                            <label>Estado: Finalizado</label>
                                            break;
                                    }
                                </div>
                                <div class="col-md-4 py-1 pr-2">
                                    <img src="@(producto.HistorialCompra.Producto.Imagenes.FirstOrDefault())" class="card-img" alt="...">
                                </div>

                            </div>
                            <br /><br /><br />
                            <div class="row">
                                <div class="col-md-4 py-4 pl-5">
                                    <form method="post">
                                        <input type="hidden" asp-for="HistorialCompra.Id" value="@(producto.HistorialCompra.Id)" />
                                        @if (producto.HistorialCompra.EstadoCompra == Models.Enums.EstadoCompra.PendienteEnvio)
                                        {
                                            <button type="submit" class="btn btn-danger" asp-page-handler="cancelar">Cancelar Pedido</button>
                                        }
                                    </form>
                                </div>
                                <div class="col-md-4 ">
                                    <h6 id="titulo">Califica este producto</h6>
                                    <div class="btn-group mr-2" role="group" aria-label="First group">
                                        <form method="get">
                                            <button type="submit" class="btn btn-secondary @(((int)producto.ProductoPuntuacion) == 1 ? "active" : null)" asp-page-handler="calificar" asp-route-id="@(producto.HistorialCompra.ProductoId)" asp-route-valor="1">1</button>
                                            <button type="submit" class="btn btn-secondary @(((int)producto.ProductoPuntuacion) == 2 ? "active" : null)" asp-page-handler="calificar" asp-route-id="@(producto.HistorialCompra.ProductoId)" asp-route-valor="2">2</button>
                                            <button type="submit" class="btn btn-secondary @(((int)producto.ProductoPuntuacion) == 3 ? "active" : null)" asp-page-handler="calificar" asp-route-id="@(producto.HistorialCompra.ProductoId)" asp-route-valor="3">3</button>
                                            <button type="submit" class="btn btn-secondary @(((int)producto.ProductoPuntuacion) == 4 ? "active" : null)" asp-page-handler="calificar" asp-route-id="@(producto.HistorialCompra.ProductoId)" asp-route-valor="4">4</button>
                                            <button type="submit" id="mayorCal" class="btn btn-secondary @(((int)producto.ProductoPuntuacion) == 5 ? "active" : null)" asp-page-handler="calificar" asp-route-id="@(producto.HistorialCompra.ProductoId)" asp-route-valor="5">5</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <h6 id="titulo" class="">
                                        Promedio
                                    </h6>
                                    <b>3,8</b>
                                </div>
                            </div>
                        </div>
                        <hr />


                    }
                }




            </div>
        </div>



    </div>

</div>